### ISSUE TITLE
Version conflict with the intl package

### ISSUE THREAD

**Issue by apps-auth** [andreciornavei/flutter-input-sheet#2]
Hello, I would like to use this package in my project, however it has version conflict with the intl package. 

Because *my_project_name* depends on input_sheet ^0.0.2 which depends on intl ^0.15.8, intl ^0.15.8 is required.

So, because *my_project_name* depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because *my_project_name* depends on intl ^0.16.1, version solving failed.)
exit code 1

**Comment by andreciornavei** [comment]
Hello, in this situations i will try to keep all the packages updated, but in some cases, you could need it emergencially and cannot wait for new versions.

So, you can use a property in your pubspec.yaml named `dependency_overrides`, this property override the dependency versions used in dependencies packages.

Then, to solve it for now until the next version, you can use the code below in your pubspec:

```yaml
dependency_overrides:
  intl: ^0.16.1
```

**Comment by apps-auth** [comment]
Okay, thanks, I'll try.
Wouldn't modifying the version to '  intl: ">=0.15.0 <1.0.0" ' solve the problem?

**Comment by andreciornavei** [comment]
Of course, it will be fixed on next release. Thanks.

**Comment by andreciornavei** [comment]
Implemented intl package to latest version on release 0.1.0

**Comment by iamkoami** [comment]
Hello, I would like to use this package (input_sheet: ^0.2.1) on my project but have conflit conflict with the intl package intl ^0.17.0.
Any solution to resolve that ? Thanks
