### ISSUE TITLE
Maxlines Error in longtext

### ISSUE THREAD

**Issue by Subfly** [andreciornavei/flutter-input-sheet#6]
Basic flutter issue which returns this. Can you fix this as soon as possible?

<img width="393" alt="Screen Shot 2020-06-18 at 14 23 31" src="https://user-images.githubusercontent.com/33986248/85014634-4a0be080-b16f-11ea-8698-1026833c4d8d.png">

**Comment by andreciornavei** [comment]
Hello Subfly, i fixed this bug based on error in yours print because i couldn't reproduce it in my environment... So check if is everything ok now and give me a feedback ok? Thanks for collaborate with this project.

**Comment by Subfly** [comment]
Yep! Bug fixed. Thanks! 
Additionaly, Im running on 1.20 dev env. Maybe, that was the issue. Anyway, this saved you for future.
